# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Flaire of Machine Learning
email: f.kratzert@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Keeping progress recorded...
baseurl: "" # the subpath of your site, e.g. /blog
url: "kratzert.github.io" # the base hostname & protocol for your site
twitter_username: fkratzert
github_username:  kratzert
google_analytics: 'UA-96660715-1'

# Build settings
markdown: kramdown
kramdown:
  input: GFM
